

BLAZE: 100
CREEPER: 100
GHAST: 100
MAGMA CUBE: 100
SILVERFISH: 100
SKELETON: 100
SLIME: 100
ZOMBIE: 100
ZOMBIE VILLAGER: 100
DROWNED: 100
WITHER SKELETON: 100
WITCH: 100
VINDICATOR: 100
EVOKER: 100
PILLAGER: 100
RAVAGER: 100
VEX: 100
PIGLIN BRUTE: 100
HOGLIN: 100
ZOGLIN: 100
ENDERMITE: 100
GUARDIAN: 100
SHULKER: 100
HUSK: 100
STRAY: 100

ENDERMAN: 100
PIGLIN: 100
SPIDER: 100
CAVE SPIDER: 100
ZOMBIFIED PIGLIN: 100
BEE: 100
WOLF: 100
LLAMA: 100
TRADER LLAMA: 100

CHICKEN: 100
COW: 100
MOOSHROOM: 100
PIG: 100
SHEEP: 100
SQUID: 100
VILLAGER: 100
WANDERING TRADER: 100
BAT: 100
HORSE: 100
STRIDER: 100
FOX: 100
RABBIT: 100
PARROT: 100
COD: 100
SALMON: 100
PUFFERFISH: 100
TROPICAL FISH: 100
